DjangoAXF/AXF/AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('App.urls', namespace='axf')),

]

DjangoAXF/AXF/App/urls.py
from django.conf.urls import url
from App.views import *

urlpatterns = [
    url(r'^home/$', home, name='home'),
    url(r'^market/$', market, name='market'),
    url(r'^cart/$', cart, name='cart'),
    url(r'^mine/$', mine, name='mine'),

    url(r'^market/(\d+)/(\d+)/(\d+)/$', market_with_params, name='market_with_params'),
    url(r'^taobao/(.+)/$', taobao, name='taobao'),
    url(r'^register/$', register, name='register'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^checkusername/$', check_username, name='check_username'),

    url(r'^addtocart/$', add_to_cart, name='add_to_cart'),
    url(r'^addnum/$', add_num, name='add_num'),
    url(r'^subnum/$', sub_num, name='sub_num'),
    url(r'^changeselectstate/$', change_select_state, name='change_select_state'),
    url(r'^cartdelgoods/$', cart_del_goods, name='cart_del_goods'),
    url(r'^cartchangeselect/$', cart_change_select, name='cart_change_select'),

    url(r'^generateorder/$', generate_order, name='generate_order'),
    url(r'^orderinfo/(\d+)/$', order_info, name='order_info'),
    url(r'^changeorderstatus/$', change_order_status, name='change_order_status'),
    url(r'^orderwaitpay/$', order_wait_pay, name='order_wait_pay'),
    url(r'^orderpaid/$', order_paid, name='order_paid'),

]

DjangoAXF/AXF/templates/mine/mine.html
{% extends 'base_main.html' %}
{% load static %}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/mine/mine.css' %}">
{% endblock %}

{% block content %}
    <div id="mine">

        {# 顶部的个人信息 #}
        <div class="fixed">
            {% if username and icon %}
                <img src="{% static icon %}"/>
            {% else %}
                <span class="glyphicon glyphicon-user"></span>
            {% endif %}

            {% if username %}
                <a href="#">{{ username }}</a>
            {% else %}
                <a href="{% url 'axf:login' %}" style="color: dodgerblue">登录</a>
            {% endif %}
            <p>
                <span class="glyphicon glyphicon-fire"></span>
                <span>等级</span>
            </p>

            <div id="regis">
                {% if username %}

                {% else %}
                    <a href="{% url 'axf:register' %}" style="color: dodgerblue">注册</a>
                {% endif %}
            </div>

            <p>
                <span class="glyphicon glyphicon-heart"></span>
                <span>收藏</span>
            </p>
        </div>

        {#订单信息#}
        <div class="mine mine2">
            <p>我的订单 <a href="#">更多&gt</a></p>

            <div id="nav">
                <ul>
                    <li>
                        <a href="{% url 'axf:order_wait_pay' %}">
                            <dl>
                                <dt class="glyphicon glyphicon-usd"></dt>
                                <span>待付款</span>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'axf:order_paid ' %}">
                            <dl>
                                <dt class=" glyphicon glyphicon-envelope"></dt>
                                <dd>待收货</dd>
                            </dl>
                        </a>
                    </li>

                    <li>
                        <dl>
                            <dt class="glyphicon glyphicon-pencil"></dt>
                            <dd>待评价</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt class="glyphicon glyphicon-retweet"></dt>
                            <dd>退款/售后</dd>
                        </dl>
                    </li>
                </ul>
            </div>

            <menu>
                <ul>
                    <li>
                        <dl>
                            <dt class="glyphicon glyphicon-bullhorn"></dt>
                            <dd>积分商城</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt class="glyphicon glyphicon-credit-card"></dt>
                            <dd>优惠券</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt class="glyphicon glyphicon-import"></dt>
                            <dd>收货地址</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt class="glyphicon glyphicon-phone-alt"></dt>
                            <dd>客户反馈</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt class="glyphicon glyphicon-certificate"></dt>
                            <dd>关于我们</dd>
                        </dl>
                    </li>
                </ul>
            </menu>
            {#            退出登录#}
            {% if username %}
                <p>
                    <a href="{% url 'axf:logout' %}" style="color: dodgerblue">注销</a>
                </p>
            {% endif %}

        </div>
    </div>
{% endblock %}