DjangoAXF/AXF/AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('App.urls', namespace='axf')),

]

DjangoAXF/AXF/App/urls.py
from django.conf.urls import url
from App.views import *

urlpatterns = [
    url(r'^home/$', home, name='home'),
    url(r'^market/$', market, name='market'),
    url(r'^cart/$', cart, name='cart'),
    url(r'^mine/$', mine, name='mine'),

    url(r'^market/(\d+)/(\d+)/(\d+)/$', market_with_params, name='market_with_params'),
    url(r'^taobao/(.+)/$', taobao, name='taobao'),
    url(r'^register/$', register, name='register'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^checkusername/$', check_username, name='check_username'),

    url(r'^addtocart/$', add_to_cart, name='add_to_cart'),
    url(r'^addnum/$', add_num, name='add_num'),
    url(r'^subnum/$', sub_num, name='sub_num'),
    url(r'^changeselectstate/$', change_select_state, name='change_select_state'),
    url(r'^cartdelgoods/$', cart_del_goods, name='cart_del_goods'),
    url(r'^cartchangeselect/$', cart_change_select, name='cart_change_select'),

    url(r'^generateorder/$', generate_order, name='generate_order'),
    url(r'^orderinfo/(\d+)/$', order_info, name='order_info'),
    url(r'^changeorderstatus/$', change_order_status, name='change_order_status'),
    url(r'^orderwaitpay/$', order_wait_pay, name='order_wait_pay'),
    url(r'^orderpaid/$', order_paid, name='order_paid'),

]

DjangoAXF/AXF/templates/market/market.html
{% extends 'base_main.html' %}
{% load static %}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/market/market.css' %}">
{% endblock %}

{% block extJS %}
    <script src="{% static 'app/market/market.js' %}"></script>
{% endblock %}


{% block content %}
    <div id="market">

        {#    左侧的主分类数据 #}
        <aside>
            <ul>
                {% for foodtype in foodtypes %}
                    <li>
                        <a href="{% url 'axf:market_with_params' foodtype.typeid '0' '0' %}">{{ foodtype.typename }}</a>
                        {% if foodtype.typeid == typeid %}
                            <span class="yellowSlide"></span>
                        {% endif %}

                    </li>
                {% endfor %}
            </ul>
        </aside>

        {#  右边的商品数据  #}
        <section>

            {#  右边的导航  #}
            <nav>
                <ul>
                    <li id="all_type">
                    <span>全部类型
                        <span id="all_type_icon" class="glyphicon glyphicon-chevron-down"></span>
                    </span>
                    </li>
                    <li id="sort_rule">
                    <span>综合排序
                         <span id="sort_rule_icon" class="glyphicon glyphicon-chevron-down"></span>
                    </span>
                    </li>
                </ul>
            </nav>

            {#        右边的商品#}
            <menu>
                <ul>
                    {% for goods in goods_list %}
                        <li>
                            <a href="{% url 'axf:taobao' goods.productlongname %}">
                                <img src="{{ goods.productimg }}" alt="">
                                <div class="shoppingInfo">
                                    <h6>{{ goods.productlongname }}</h6>
                                    <p class="detailTag"><span>精选</span>
                                    </p>
                                    <p class="unit">{{ goods.specifics }}</p>
                                    <p class="price">
                                        <span>￥{{ goods.price }}</span>
                                        <s>￥{{ goods.marketprice }}</s>
                                    </p>
                                </div>
                            </a>
                            <section>
                                <button class="subnum">-</button>
                                <span class="num">1</span>
                                <button class="addnum">+</button>
                            </section>
                            <a href="#" goodsid="{{ goods.id }}" class="addtocart">加入购物车</a>
                        </li>
                    {% endfor %}

                </ul>

                {#    全部类型#}
                <div id="all_type_container">
                    <div>
                        {% for child_type in all_child_type %}
                            <a href="{% url 'axf:market_with_params' typeid child_type.1 '06' %}">
                                <span>{{ child_type.0 }}</span>
                            </a>
                        {% endfor %}
                    </div>
                </div>

                {#        排序规则#}
                <div id="sort_rule_container">
                    <div>
                        <a href="{% url 'axf:market_with_params' typeid cid '0' %}">
                            <span>综合排序</span>
                        </a>
                        <a href="{% url 'axf:market_with_params' typeid cid '1' %}">
                            <span>销量排序</span>
                        </a>
                        <a href="{% url 'axf:market_with_params' typeid cid '2' %}">
                            <span>价格降序</span>
                        </a>
                        <a href="{% url 'axf:market_with_params' typeid cid '3' %}">
                            <span>价格升序</span>
                        </a>
                    </div>
                </div>

            </menu>

        </section>


    </div>
{% endblock %}